# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: ..
markdown: kramdown
permalink: /:title/
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sugarbeautyphotography.com"
# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
# UI configs
title: "Shots by Sweet Street Spark"
subtitle: "A chapter from my life"
author:  "Sweet Street Spark"
header:
 title: "Shots"
 subtitle: "by D. / Sweet Street Spark"
footer:
 name: "Hello World! 👋'"
 bio: "Not an artsy person at all, but I am into photography and fashion. I also write to <a href='https://indieyespls.com'>IndieYesPls</a>"
social_urls:
  instagram: "https://www.instagram.com/sweet.street.spark/"
